### ISSUE TITLE
Add OpenStack Glance Support

### ISSUE THREAD

**Issue by briandowns** [fatih/images#20]
http://docs.openstack.org/developer/glance/

**Comment by briandowns** [comment]
@fatih if this hasn't been started on by anyone, I'd like to take a stab at it.

**Comment by fatih** [comment]
Would be awesome @briandowns :+1: . Just check out the other providers I think you have a plenty of examples. 

Besides that is there any third party provider we can use for testing the OpenStack API directly? I think Rackspace uses their own modified API, so I'm not sure :)

**Comment by briandowns** [comment]
I've been using github.com/rackspace/gophercloud recently for vanilla OpenStack deployments as well as MetaCloud based deployments and it's proven to be pretty good.  There's also the stackforge/golang-client.  The former doesn't support Glance directly though the latter does.  Between the two there's mixed functionality.  I'll play around and see which will be best.

**Comment by fatih** [comment]
Sounds good. I think we should go with `gophercloud`. I've used it too earlier. It's the official one, at least we can add back support to it so everyone can benefit if something goes wrong or needs improvement.

**Comment by briandowns** [comment]
That definitely works for me.  Should have something soon.  Thanks!
